query categories($key: ID!, $limit: Int, $start: Int) {
    category(id: $key)  {
        id,
        name
        homes(limit: $limit, start: $start) {
            id,
            title,
            price,
            pics {
                url
            }
        }
    }
}