query homesConnection {
  homesConnection {
    aggregate {
      totalCount
    }
    groupBy {
      category {
        key
        connection {
          aggregate {
            count
          }
        }
      }
    }
  }
}